### ISSUE TITLE
Multi-core use on QEMU

### ISSUE THREAD

**Issue by arminveres** [tonistiigi/binfmt#145]
Is it possible to use multiple cores or pass a flag to QEMU, because when running on arm-v7, armbian 23.8, qemu only utilizes one core, and stays pinned at 100%.

**Comment by tonistiigi** [comment]
I'm not aware of such a limitation. Is it specific to arm-v7?

**Comment by moliyadi** [comment]
Using arm64 also has similar problems, only two cores can be used 100% when compiling, the other cores are idle.

**Comment by tonistiigi** [comment]
Reopen when you have some proof
