### ISSUE TITLE
feature request: binfmt as a docker container "service"

### ISSUE THREAD

**Issue by prokrypt** [tonistiigi/binfmt#146]
Would be nice to have it able to automatically run every time docker is started. Maybe add in a shell script and have it "sleep inf"? Perhaps have a special env variable to enable this mode?

**Comment by tonistiigi** [comment]
This repo is specifically for distribution via container images. If you want to run as a service you are probably better off trying some packages that your distro provides.

If the request is for some systemd unit files that run `docker run` internally then if they are provided we could put it in a contrib section of this repo, or if they live in some external place we could link to them from the readme.
