### ISSUE TITLE
Do not use passthrough mode?

### ISSUE THREAD

**Issue by gulien** [tonistiigi/binfmt#148]
Hey there 👋 

So, let's first start by saying I'm out of my depth here, but, still, it might be interesting for you to have the information.

I've been building a Docker image with QEMU to target many platforms (using `docker/setup-qemu-action@v3`). Long story short, I've encountered a bug with `chromium` on the `armhf` architecture at build stage, and filled an issue in the Debian bug tracker.

While investigating, the maintainer found out some "anomalies" regarding QEMU/binfmt (see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1055765#40).  Also:

> As far as qemu, I'd suggest filing a bug on that binfmt project to not 
use passthrough mode; I'm not sure if it should be something 
decided/set at build time, or if there's a way to get commandline 
arguments to qemu when executing binaries using the kernel's binfmt 
interface. Either way, that seems like something to discuss with the 
project author. 

I won't be able to debate anything on this subject (unless you're ready to guide me),  but maybe you'll find something useful.

**Comment by tonistiigi** [comment]
🤔 We don't use qemu for isolation or live migration in this context. You can set the CPU configuration yourself (not recommended but works) by just defining the `QEMU_CPU`, for example in your Dockerfile. In Docker build, you are protected by the container sandbox, not by the emulator.

**Comment by gulien** [comment]
Thanks for the details 👍 I was off topic I guess, sorry for that.
