### ISSUE TITLE
The command “–uninstall mips64le” cannot be used to uninstall mips64le.

### ISSUE THREAD

**Issue by simon-cw-hsu** [tonistiigi/binfmt#180]
It seems that the parameters passed in “mips64le” were misinterpreted as other text "mips64el".

Simons-MacBook-Air ~ % docker run --rm --privileged tonistiigi/binfmt --uninstall **mips64le**
uninstalling: **mips64el** not found
{
  "supported": [
    "linux/arm64",
    "linux/amd64",
    "linux/386",
    "linux/mips64le",
    "linux/arm/v7",
    "linux/arm/v6"
  ],
  "emulators": [
    "mips64le",
    "qemu-arm",
    "qemu-i386",
    "qemu-x86_64"
  ]
}

**Comment by tonistiigi** [comment]
> "emulators": [
"mips64le",

Are you sure this was installed with this repository? It should be `qemu-mips64el` then.

Seemed to work fine for me:

```
» docker run -it --rm --privileged tonistiigi/binfmt --install mips64le
installing: mips64le OK

...
  "emulators": [
    "mac-macho-arm64",
    "mac-macho-x86_64",
    "mac-universal-arm64",
    "mac-universal-x86_64",
    "qemu-arm",
    "qemu-i386",
    "qemu-mips64el",
...

» docker run -it --rm --privileged tonistiigi/binfmt --uninstall mips64le
uninstalling: mips64el OK
{
```
