### ISSUE TITLE
Support for linux/amd64/v4

### ISSUE THREAD

**Issue by barbetb** [tonistiigi/binfmt#198]
Can we get support for linux/amd64/v4 ?

I have this issue:
```ERROR: failed to solve: no support for running processes with linux/amd64/v4 platform, supported: linux/amd64, linux/amd64/v2```

Regards,

Rick

**Comment by tonistiigi** [comment]
This would need to be supported by qemu. But looks unlikely that the CPU features that are required for v4 can be emulated.
