### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by whynowy** [tonistiigi/binfmt#46]
Could you share what the license used for the image?

**Comment by tonistiigi** [comment]
Code in this repo is MIT. For license info of qemu see https://wiki.qemu.org/License

**Comment by whynowy** [comment]
Thanks!

**Comment by BenTheElder** [comment]
This issue seems to be the only place where MIT is mentioned, perhaps it's worth adding a LICENSE file? 😅

**Comment by BenTheElder** [comment]
Thanks!
