### ISSUE TITLE
Running containers with different architecture

### ISSUE THREAD

**Issue by michaelact** [tonistiigi/binfmt#64]
Hi @tonistiigi and other Maintainers.

Thank you in advance for making this **binfmt**, it's very useful for building multi architecture image. 😄

I want to ask something, I have tried to run this command` docker run --privileged --rm tonistiigi/binfmt --install all` in my Virtual Machine. Because I have an image with a different architecture, so I want the image to running as a container even though it's a different architecture.

But until I realized the **resource usage was higher (also never down) than when the image was run on the same architecture**. Is there any explanation for this?

**Comment by tonistiigi** [comment]
This is a software emulator that converts instructions from one CPU architecture into another while running so it is expected to have lower performance. Especially when running CPU-intensive applications. When you are running a container in production you should pretty much always only run native containers. But this is sometimes fine for building images or one-off testing. For a different approach for building multi-arch with native speeds if you have a slow compilation step you might want to look up https://github.com/tonistiigi/xx instead
