### ISSUE TITLE
Regression in qemu 6.1.0 aarch64-on-x86 emulator

### ISSUE THREAD

**Issue by sdwr98** [tonistiigi/binfmt#72]
Hello,

This is coming from https://github.com/ibmruntimes/Semeru-Runtimes/issues/11 - I think I've tracked the issue down to the emulators installed by binfmt 6.1.0.  

To reproduce the issue, use this Dockerfile: 

```
FROM --platform=linux/arm64 centos:latest@sha256:65a4aad1156d8a0679537cb78519a17eb7142e05a968b26a5361153006224fdc

RUN  yum install -y tar gzip wget alsa-lib dejavu-sans-fonts fontconfig freetype libX11 libXext libXi libXrender libXtst
RUN  wget https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK8_aarch64_linux_Personal/33/OpenJ9-JDK8-aarch64_linux-20211206-231001.tar.gz && \
     tar -C /opt -xvf OpenJ9-JDK8-aarch64_linux-20211206-231001.tar.gz
RUN  /opt/j2sdk-image/bin/java -version
```
and run the following on an x86 machine: 

```
docker run --privileged --rm tonistiigi/binfmt:qemu-v6.1.0 --uninstall "qemu-*"
docker run --privileged --rm tonistiigi/binfmt:qemu-v6.1.0 --install all
docker build --rm --no-cache --platform=linux/arm64 -f Dockerfile .
```

The last step in the build file should fail with a java error.  

If you change the above steps to use `qemu-6.0.0`, the build succeeds.  

If it helps, we traced the issue to an ENOSYS error when the JVM is calling `pthread_create`. 

Thanks!

**Comment by tonistiigi** [comment]
Looks like the same case as #69? Please check with the latest release https://github.com/tonistiigi/binfmt/releases/tag/deploy%2Fv6.1.0-21

**Comment by sdwr98** [comment]
That was it - thank you!
