### ISSUE TITLE
README: update instructions to cover "permanent" install instructions

### ISSUE THREAD

**Issue by myitcv** [tonistiigi/binfmt#75]
I'm finding that I need to run:

```
docker run --privileged --rm tonistiigi/binfmt --install all
```

after every machine reboot.

Am I holding something wrong here? 

Or are there instructions that make the install "permanent"?

**Comment by tonistiigi** [comment]
Yes, you do need to run the image again. We don't change anything in your host, eg. install a service that would rerun on boot. Some distro packages I believe do that if you are looking for alternatives.

**Comment by myitcv** [comment]
Thanks. 

Regarding https://github.com/moby/buildkit/issues/2541#issuecomment-1005690647, I believe I've narrowed down the issue to `qemu` requiring some config/patching to work with buildkit. So for now will continue to use the `--install` workaround until I can get buildkit to work with my native `qemu` installation (which will persist between reboots).
