### ISSUE TITLE
Is there any real underlying difference in platform between linux/arm64 and linux/arm64/v8?

### ISSUE THREAD

**Issue by ju2wheels** [tonistiigi/binfmt#77]
I noticed on Docker Hub that for arm64 images have either linux/arm64 or linux/arm64/v8. Is there currently any real difference between the two or is one currently just the more explicit form of the other and a means for future proofing the platform specification when we get a newer arm64 variant than v8?

**Comment by tonistiigi** [comment]
No, they are the same. Normalized form is without the variant https://github.com/containerd/containerd/blob/ab8d99cf4bec7fe4225f73162be3da338e925791/platforms/database.go#L96

**Comment by ju2wheels** [comment]
Great, thank you.
