### ISSUE TITLE
"exec format error" after reboot. How to avoid reinstallation on Raspberry Pi?

### ISSUE THREAD

**Issue by Nitrooo** [tonistiigi/binfmt#85]
I have a few containers on my Raspberry Pi that run amd64 emulators:
`docker run -d --restart always --platform linux/amd64 example/example`
Whenever I reboot I have to reinstall `binfmt` with:
`docker run --privileged --rm tonistiigi/binfmt --install all`
Otherwise I get `exec /bin/sh: exec format error` inside my containers.
That's really annoying. Is there a way to avoid this?

**Comment by tonistiigi** [comment]
This is expected. You need to run the install command again after reboot. The best way for doing that depends on your distro etc.

**Comment by Nitrooo** [comment]
I ended up making a systemd service for that.

Thanks.
